using System.Text.Json;
using ErgoProxy.Core.Platform;
using ErgoProxy.Core.Tunnel.Native;

namespace ErgoProxy.Core.Tunnel.Platform;

public sealed class LinuxTunnelPlatform : ITunnelPlatform
{
    private const string JournalPath = "/run/ergoproxy/applied_state.json";
    private const string ResolvBackupPath = "/run/ergoproxy/resolv.conf.bak";

    public bool IsSupported => LinuxNative.IsLinux;
    public string? UnsupportedReason => IsSupported ? null : "ErgoProxy device-wide tunnel is currently supported on Linux.";
    public string PlatformName => "Linux (Policy Routing + TUN)";

    public async Task SetupTunnelNetworkAsync(
        TunnelAddressing addressing,
        string? proxyHost,
        int proxyPort,
        CancellationToken ct = default)
    {
        EnsureRunDir();

        // 1. Bring interface up and assign IP address
        await RunCommandAsync("ip", ["link", "set", "dev", addressing.InterfaceName, "up", "mtu", addressing.Mtu.ToString()], ct).ConfigureAwait(false);
        await RunCommandAsync("ip", ["addr", "replace", $"{addressing.InterfaceAddress}/{addressing.PrefixLength}", "dev", addressing.InterfaceName], ct).ConfigureAwait(false);

        // Optional IPv6 link address
        await RunCommandAsync("ip", ["-6", "addr", "replace", $"{addressing.InterfaceAddressV6}/{addressing.PrefixLengthV6}", "dev", addressing.InterfaceName], ct).ConfigureAwait(false);

        // 2. Policy routing for device-wide capture and loop prevention
        // First ensure any old rules from table are gone
        await CleanStaleRulesAsync(addressing, ct).ConfigureAwait(false);

        // Main table suppress rule so local/LAN traffic stays on physical interface
        await RunCommandAsync("ip", ["rule", "add", "table", "main", "suppress_prefixlength", "0", "priority", (addressing.RulePriority - 1).ToString()], ct).ConfigureAwait(false);

        // Traffic NOT marked with fwMark routes through table 4552
        var fwMarkHex = $"0x{addressing.FwMark:x}";
        await RunCommandAsync("ip", ["rule", "add", "not", "fwmark", fwMarkHex, "table", addressing.RouteTable.ToString(), "priority", addressing.RulePriority.ToString()], ct).ConfigureAwait(false);

        // Default route in table 4552 goes to TUN interface
        await RunCommandAsync("ip", ["route", "replace", "default", "dev", addressing.InterfaceName, "table", addressing.RouteTable.ToString()], ct).ConfigureAwait(false);

        // 3. DNS configuration (Fake-IP resolver on addressing.DnsAddress)
        var usedResolved = false;
        var resolvectlCheck = await ProcessRunner.RunAsync("resolvectl", ["--version"], TimeSpan.FromSeconds(2), ct).ConfigureAwait(false);
        if (resolvectlCheck.ExitCode == 0)
        {
            var resDns = await RunCommandAsync("resolvectl", ["dns", addressing.InterfaceName, addressing.DnsAddress.ToString()], ct).ConfigureAwait(false);
            var resDom = await RunCommandAsync("resolvectl", ["domain", addressing.InterfaceName, "~."], ct).ConfigureAwait(false);
            usedResolved = resDns && resDom;
        }

        if (!usedResolved && File.Exists("/etc/resolv.conf"))
        {
            try
            {
                if (!File.Exists(ResolvBackupPath))
                {
                    File.Copy("/etc/resolv.conf", ResolvBackupPath, overwrite: true);
                }
                var newResolv = $"# Generated by ErgoProxy\nnameserver {addressing.DnsAddress}\n";
                await File.WriteAllTextAsync("/etc/resolv.conf", newResolv, ct).ConfigureAwait(false);
            }
            catch
            {
                // Non-fatal if /etc/resolv.conf is read-only symlink
            }
        }

        // 4. Save state journal
        try
        {
            var journal = new Dictionary<string, object>
            {
                ["interface"] = addressing.InterfaceName,
                ["table"] = addressing.RouteTable,
                ["priority"] = addressing.RulePriority,
                ["fwmark"] = addressing.FwMark,
                ["used_resolved"] = usedResolved,
                ["created_at"] = DateTimeOffset.UtcNow
            };
            await File.WriteAllTextAsync(JournalPath, JsonSerializer.Serialize(journal), ct).ConfigureAwait(false);
        }
        catch
        {
            // Ignore journal write error
        }
    }

    public async Task TearDownTunnelNetworkAsync(TunnelAddressing addressing, CancellationToken ct = default)
    {
        // 1. Revert DNS
        try
        {
            await RunCommandAsync("resolvectl", ["revert", addressing.InterfaceName], ct).ConfigureAwait(false);
        }
        catch { }

        if (File.Exists(ResolvBackupPath))
        {
            try
            {
                File.Copy(ResolvBackupPath, "/etc/resolv.conf", overwrite: true);
                File.Delete(ResolvBackupPath);
            }
            catch { }
        }

        // 2. Clean routing rules and routes
        await CleanStaleRulesAsync(addressing, ct).ConfigureAwait(false);

        // 3. Bring interface down
        await RunCommandAsync("ip", ["link", "set", "dev", addressing.InterfaceName, "down"], ct).ConfigureAwait(false);

        // 4. Remove journal
        if (File.Exists(JournalPath))
        {
            try { File.Delete(JournalPath); } catch { }
        }
    }

    public async Task CleanStaleStateAsync(TunnelAddressing addressing, CancellationToken ct = default)
    {
        await CleanStaleRulesAsync(addressing, ct).ConfigureAwait(false);
        if (File.Exists(ResolvBackupPath))
        {
            try
            {
                File.Copy(ResolvBackupPath, "/etc/resolv.conf", overwrite: true);
                File.Delete(ResolvBackupPath);
            }
            catch { }
        }
        if (File.Exists(JournalPath))
        {
            try { File.Delete(JournalPath); } catch { }
        }
    }

    private async Task CleanStaleRulesAsync(TunnelAddressing addressing, CancellationToken ct)
    {
        // Flush table routes
        await RunCommandAsync("ip", ["route", "flush", "table", addressing.RouteTable.ToString()], ct).ConfigureAwait(false);

        // Delete fwmark rules (loop until none left)
        var fwMarkHex = $"0x{addressing.FwMark:x}";
        for (var i = 0; i < 5; i++)
        {
            var res = await ProcessRunner.RunAsync("ip", ["rule", "del", "not", "fwmark", fwMarkHex, "table", addressing.RouteTable.ToString()], TimeSpan.FromSeconds(2), ct).ConfigureAwait(false);
            if (res.ExitCode != 0) break;
        }

        // Delete suppress rule
        for (var i = 0; i < 5; i++)
        {
            var res = await ProcessRunner.RunAsync("ip", ["rule", "del", "table", "main", "suppress_prefixlength", "0"], TimeSpan.FromSeconds(2), ct).ConfigureAwait(false);
            if (res.ExitCode != 0) break;
        }
    }

    private static void EnsureRunDir()
    {
        try
        {
            if (!Directory.Exists("/run/ergoproxy"))
            {
                Directory.CreateDirectory("/run/ergoproxy");
            }
        }
        catch { }
    }

    private static async Task<bool> RunCommandAsync(string cmd, string[] args, CancellationToken ct)
    {
        var res = await ProcessRunner.RunAsync(cmd, args, TimeSpan.FromSeconds(5), ct).ConfigureAwait(false);
        return res.ExitCode == 0;
    }
}
